/*
 * SENTEC / Signal / Structure
 * The hero identity is constructed as animated layers rather than a flat image:
 * compass frame, engineering field icons, central mechanism, signal nodes, and lockup.
 */
import { useEffect, useState } from "react";
import { ArrowDownRight, ArrowUpRight, ChevronRight, Cpu, FlaskConical, Gauge, Menu, Radio, X } from "lucide-react";

const logoAsset = "/manus-storage/SENTECNEWWHITELOGO_2ba86ec2.webp";
const heroTexture = "/manus-storage/sentec-hero-texture_fbda6e33.png";
const aboutTexture = "/manus-storage/sentec-about-texture_326034d4.png";
const projectTexture = "/manus-storage/sentec-project-texture_223a946e.png";

const navItems = [{ label: "Home", href: "#home" }, { label: "About", href: "#about" }, { label: "Team", href: "/team" }, { label: "Events", href: "/events" }, { label: "Partners", href: "/partners" }, { label: "Gallery", href: "/gallery" }, { label: "Contact Us", href: "/contact" }];
const orbitNodes = [
  { label: "ROBOTICS", icon: Cpu, className: "node-one", accent: "01" },
  { label: "RESEARCH", icon: FlaskConical, className: "node-two", accent: "02" },
  { label: "SYSTEMS", icon: Radio, className: "node-three", accent: "03" },
  { label: "IMPACT", icon: Gauge, className: "node-four", accent: "04" },
];

function AnimatedMark() {
  return (
    <div className="mark-stage" aria-label="Animated SENTEC engineering system">
      <div className="mark-scanline" /><div className="reference-logo-stack" aria-hidden="true"><img className="reference-logo reference-logo-base" src={logoAsset} alt="" /><img className="reference-logo reference-logo-layer layer-scan" src={logoAsset} alt="" /><img className="reference-logo reference-logo-layer layer-frame" src={logoAsset} alt="" /><img className="reference-logo reference-logo-layer layer-upper" src={logoAsset} alt="" /><img className="reference-logo reference-logo-layer layer-core" src={logoAsset} alt="" /><img className="reference-logo reference-logo-layer layer-wordmark" src={logoAsset} alt="" /><img className="reference-logo reference-logo-layer element-bolt" src={logoAsset} alt="" /><img className="reference-logo reference-logo-layer element-bridge" src={logoAsset} alt="" /><img className="reference-logo reference-logo-layer element-tower" src={logoAsset} alt="" /><img className="reference-logo reference-logo-layer element-sensor" src={logoAsset} alt="" /><img className="reference-logo reference-logo-layer element-monitor" src={logoAsset} alt="" /><img className="reference-logo reference-logo-layer element-flask" src={logoAsset} alt="" /><img className="reference-logo reference-logo-layer element-gear" src={logoAsset} alt="" /><img className="reference-logo reference-logo-layer element-core" src={logoAsset} alt="" /></div>
      <svg className="logo-machine" viewBox="0 0 443 470" role="img" aria-label="SENTEC engineering system">
        <defs><filter id="orangeGlow"><feGaussianBlur stdDeviation="2.5" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter></defs>
        <g className="logo-compass" fill="none" stroke="rgba(244,241,235,.82)" strokeWidth="1.3"><circle cx="230" cy="210" r="176" /><circle cx="230" cy="210" r="145" strokeDasharray="2 9" /><circle className="symbol-orbit" cx="230" cy="210" r="128" stroke="rgba(244,241,235,.25)" strokeDasharray="1 12" /><circle cx="230" cy="210" r="104" stroke="rgba(241,90,36,.68)" strokeDasharray="34 12" /><path d="M230 25v36M230 395v36M45 210h36M379 210h36" /><path d="M105 85l24 24M331 311l24 24M355 85l-24 24M129 311l-24 24" stroke="rgba(241,90,36,.9)" /></g>
        <g className="logo-spokes" stroke="rgba(244,241,235,.55)" strokeWidth="1"><path d="M230 54v312M74 210h312" strokeDasharray="5 11" /><path d="M120 100l220 220M340 100L120 320" strokeDasharray="2 14" /></g>
        <g className="logo-field field-bolt radial-anchor" transform="translate(0 0)" stroke="#f15a24" fill="#f15a24" strokeWidth="1"><path d="M112 92h28l-16 35h23l-39 53 11-35H96z" /></g>
        <g className="logo-field field-bridge radial-anchor" transform="translate(0 -10)" stroke="#f15a24" fill="none" strokeWidth="3" strokeLinecap="round"><path d="M63 220h70M69 220l16-25h35l16 25M80 210h45M87 195v25M104 195v25M121 195v25" /></g>
        <g className="logo-field field-tower radial-anchor" transform="translate(0 0)" stroke="#f15a24" fill="none" strokeWidth="3" strokeLinecap="round"><path d="M326 88l-12 43h24zM319 103h14M317 115h18M308 86l18-12 18 12M326 74V53M312 60l14-9 14 9" /></g>
        <g className="logo-field field-sensor radial-anchor" transform="translate(0 0)" stroke="#f15a24" fill="none" strokeWidth="3" strokeLinecap="round"><g transform="rotate(-12 359 153)"><rect x="344" y="140" width="30" height="25" rx="3" /><path d="M350 147h19M350 154h12" /></g><path d="M381 142c7 7 7 18 0 25M389 135c12 11 12 28 0 39" /></g>
        <g className="logo-field field-monitor radial-anchor" transform="translate(17 -2)" stroke="#f15a24" fill="none" strokeWidth="3"><rect x="318" y="195" width="50" height="34" rx="2" /><path d="M331 240h24M343 229v11" /><path d="M327 205h32M327 214h20" /></g>
        <g className="logo-field field-flask radial-anchor" transform="translate(0 0)" stroke="#f15a24" fill="none" strokeWidth="3" strokeLinecap="round"><path d="M106 326v-27l11-13v-12h28v12l11 13v27c-10 10-40 10-50 0z" /><path d="M111 308h40" /></g>
        <g className="logo-field field-gear radial-anchor" transform="translate(0 -4)" stroke="#f15a24" fill="none" strokeWidth="3"><circle cx="230" cy="344" r="17" /><circle cx="230" cy="344" r="6" /><path d="M230 320v-8M230 376v-8M206 344h-8M262 344h-8M213 327l-7-7M254 361l-7-7M247 327l7-7M206 361l7-7" /></g>
        <g className="logo-core" filter="url(#orangeGlow)"><circle cx="230" cy="210" r="55" fill="rgba(8,11,13,.75)" stroke="#f15a24" strokeWidth="2" /><circle cx="230" cy="210" r="42" fill="none" stroke="rgba(244,241,235,.92)" strokeWidth="2" strokeDasharray="22 9" /><ellipse cx="230" cy="210" rx="42" ry="17" fill="none" stroke="#f15a24" strokeWidth="2" transform="rotate(35 230 210)" /><ellipse cx="230" cy="210" rx="42" ry="17" fill="none" stroke="#f15a24" strokeWidth="2" transform="rotate(-35 230 210)" /><circle cx="230" cy="210" r="8" fill="#f15a24" /><path d="M230 158v104M178 210h104" stroke="rgba(244,241,235,.75)" strokeWidth="1" /></g>
        <g className="logo-particles" fill="#f15a24"><circle cx="138" cy="210" r="4" /><circle cx="320" cy="210" r="5" /><circle cx="155" cy="292" r="3" /><circle cx="305" cy="292" r="4" /></g>
        <g className="logo-lockup" textAnchor="middle"><text className="logo-wordmark" x="230" y="430" fill="#f4f1eb" fontFamily="Rajdhani, sans-serif" fontSize="34" fontWeight="700" letterSpacing="11">SENTEC</text><path className="wordmark-rule" d="M150 441h160" fill="none" stroke="#f15a24" strokeWidth="1" /><text className="logo-tagline" x="230" y="459" fill="#f15a24" fontFamily="IBM Plex Mono, monospace" fontSize="7" letterSpacing="3">INNOVATE · ENGINEER · IMPACT</text></g>
      </svg>
      <div className="mark-sweep" /><div className="mark-caption"><span>SENTEC / FIELD SYSTEM</span><span>ACTIVE 1997—2026</span></div>
    </div>
  );
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 24); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  useEffect(() => { const targets = Array.from(document.querySelectorAll<HTMLElement>(".site-shell .motion-reveal")); const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); } }), { threshold: .12, rootMargin: "0px 0px -8% 0px" }); targets.forEach((target) => observer.observe(target)); return () => observer.disconnect(); }, []);
  return (
    <main className="site-shell">
      <div className="ambient-grid" aria-hidden="true" />
      <nav className={`site-nav ${scrolled ? "is-scrolled" : ""}`}><a className="brand-lockup" href="#home" aria-label="SENTEC home"><span className="brand-symbol"><img src={logoAsset} alt="" /></span><span className="brand-name">SENTEC<span className="brand-dot">.</span></span></a><div className={`nav-links ${menuOpen ? "is-open" : ""}`}>{navItems.map((item) => <a key={item.href} href={item.href} onClick={() => setMenuOpen(false)}>{item.label}</a>)}</div><a className="nav-cta" href="https://sentecneduet.live/login">Login <ArrowUpRight size={15} /></a><button className="menu-button" aria-label={menuOpen ? "Close menu" : "Open menu"} onClick={() => setMenuOpen((open) => !open)}>{menuOpen ? <X size={21} /> : <Menu size={21} />}</button></nav>
      <header className="hero-section" id="home" style={{ backgroundImage: `url(${heroTexture})` }}><div className="hero-overlay" /><div className="hero-content-wrap"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line" /> Student engineering society <span className="eyebrow-status">SYS.01 / ONLINE</span></div><h1>Make the<br /><em>future</em> tangible.</h1><p className="hero-lede">SENTEC is where ambitious students turn questions into working systems — through research, projects, and the kind of practice that compounds.</p><div className="hero-actions"><a className="button button-primary" href="#projects">Explore the work <ArrowUpRight size={17} /></a><a className="button button-quiet" href="#about">What we do <ChevronRight size={17} /></a></div><div className="hero-proof"><span>01</span><p>Built at NED University<br /><strong>for curious engineers</strong></p></div></div><div className="hero-visual"><AnimatedMark /></div></div><a className="scroll-cue" href="#about"><span>Scroll to inspect</span><ArrowDownRight size={17} /></a><div className="hero-side-label">24° 51′ 36″ N / 67° 00′ 36″ E</div></header>
      <section className="intro-strip motion-reveal" id="about"><div className="section-rail"><span>00</span><span>THE BRIEF</span></div><div className="intro-content"><p className="section-kicker">A platform for applied curiosity</p><h2>Move from <span>“what if?”</span><br />to <strong>“watch this.”</strong></h2><p className="intro-copy">For nearly three decades, SENTEC has brought together students who would rather test an idea than leave it in a notebook. We make room for disciplines to collide, skills to sharpen, and good work to become visible.</p><a className="text-link" href="#domains">Read the operating principles <ArrowUpRight size={16} /></a></div><div className="intro-aside" style={{ backgroundImage: `url(${aboutTexture})` }}><span>EST. 1997</span><strong>27</strong><small>years of<br />shared practice</small></div></section>
      <section className="domains-section motion-reveal" id="domains"><div className="section-heading-row"><div><p className="section-kicker">01 / Where we work</p><h2>Different fields.<br /><em>One signal.</em></h2></div><p className="section-heading-note">The best solutions rarely stay inside one discipline. Our domains are open doors into the same system.</p></div><div className="domain-list">{[{ number: "01", title: "Robotics & Automation", body: "Build machines that sense, decide, and move with intention.", icon: Cpu }, { number: "02", title: "Artificial Intelligence", body: "Turn data into better questions, clearer models, and useful predictions.", icon: Radio }, { number: "03", title: "Embedded Systems", body: "Connect the physical world through small, resilient, intelligent systems.", icon: Gauge }].map(({ number, title, body, icon: Icon }) => <article className="domain-row" key={number}><span className="domain-number">{number}</span><div className="domain-icon"><Icon size={22} /></div><div className="domain-copy"><h3>{title}</h3><p>{body}</p></div><ArrowUpRight className="domain-arrow" size={20} /></article>)}</div></section>
      <section className="projects-section motion-reveal" id="projects" style={{ backgroundImage: `url(${projectTexture})` }}><div className="projects-overlay" /><div className="projects-inner"><div className="section-heading-row projects-heading"><div><p className="section-kicker">02 / Selected systems</p><h2>Proof of<br /><em>practice.</em></h2></div><a className="button button-outline" href="#contact">See all projects <ArrowUpRight size={16} /></a></div><div className="project-grid"><article className="project-card"><div className="project-index">A / 2025</div><div className="project-card-content"><span>Autonomous systems</span><h3>Self-driving<br />rover</h3><p>A navigation platform shaped by LiDAR mapping, computer vision, and persistent iteration.</p><a href="#contact" className="text-link">View case study <ArrowUpRight size={15} /></a></div></article><article className="project-card project-card-offset"><div className="project-index">B / 2024</div><div className="project-card-content"><span>Aerospace</span><h3>CanSat<br />development</h3><p>A miniature satellite translating descent into telemetry, data, and a sharper next question.</p><a href="#contact" className="text-link">View case study <ArrowUpRight size={15} /></a></div></article></div></div></section>
      <section className="quote-section motion-reveal" id="contact"><div className="quote-mark">“</div><p className="section-kicker">03 / The reason it works</p><blockquote>“SENTEC gives students a place to develop the capabilities they will need as engineering graduates — not just the credentials.”</blockquote><div className="quote-source"><span className="quote-line" /><div><strong>Prof. Dr. Murtuza</strong><small>Faculty Incharge, SENTEC</small></div></div></section>
      <footer className="site-footer"><div className="footer-top"><a className="brand-lockup" href="#home"><span className="brand-symbol"><img src={logoAsset} alt="" /></span><span className="brand-name">SENTEC<span className="brand-dot">.</span></span></a><p>Engineering is a verb.<br />Keep it moving.</p><div className="footer-links"><a href="#about">About</a><a href="#domains">Domains</a><a href="#projects">Projects</a><a href="mailto:neduetsentec@gmail.com">Email</a></div></div><div className="footer-bottom"><span>© 2026 SENTEC / NED University</span><span>INNOVATE · ENGINEER · IMPACT</span></div></footer>
    </main>
  );
}
